# Generated by Django 5.2.6 on 2025-11-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('transfer_type', models.TextField(blank=True, null=True)),
                ('discountdiscount', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transfer',
                'managed': False,
            },
        ),
    ]
