# Generated by Django 5.2.6 on 2025-10-31 15:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'stock_category',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('last_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('update_at', models.DateTimeField(blank=True, db_column='update_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_category', models.ForeignKey(db_column='stock_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stockcategory')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recorded_at', models.DateTimeField(default=datetime.datetime.now)),
                ('stock', models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock')),
            ],
            options={
                'db_table': 'stock_price',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
