# Generated by Django 5.2.6 on 2025-10-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('variation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_price',
                'managed': False,
            },
        ),
    ]
