# Generated by Django 5.2.6 on 2025-10-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stockcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['-recorded_at']},
        ),
    ]
